/* tslint:disable */
/* eslint-disable */
/**
 * To Do App ✅
 * Simple to do application for state management demo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';

/**
 * 
 * @export
 * @interface PaginatedGroupList
 */
export interface PaginatedGroupList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedGroupList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Group>}
     * @memberof PaginatedGroupList
     */
    results?: Array<Group>;
}

/**
 * Check if a given object implements the PaginatedGroupList interface.
 */
export function instanceOfPaginatedGroupList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedGroupListFromJSON(json: any): PaginatedGroupList {
    return PaginatedGroupListFromJSONTyped(json, false);
}

export function PaginatedGroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGroupList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(GroupFromJSON)),
    };
}

export function PaginatedGroupListToJSON(value?: PaginatedGroupList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(GroupToJSON)),
    };
}

