/* tslint:disable */
/* eslint-disable */
/**
 * To Do App ✅
 * Simple to do application for state management demo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ToDo } from './ToDo';
import {
    ToDoFromJSON,
    ToDoFromJSONTyped,
    ToDoToJSON,
} from './ToDo';

/**
 * 
 * @export
 * @interface PaginatedToDoList
 */
export interface PaginatedToDoList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedToDoList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedToDoList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedToDoList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ToDo>}
     * @memberof PaginatedToDoList
     */
    results?: Array<ToDo>;
}

/**
 * Check if a given object implements the PaginatedToDoList interface.
 */
export function instanceOfPaginatedToDoList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedToDoListFromJSON(json: any): PaginatedToDoList {
    return PaginatedToDoListFromJSONTyped(json, false);
}

export function PaginatedToDoListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedToDoList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ToDoFromJSON)),
    };
}

export function PaginatedToDoListToJSON(value?: PaginatedToDoList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ToDoToJSON)),
    };
}

