/* tslint:disable */
/* eslint-disable */
/**
 * To Do App ✅
 * Simple to do application for state management demo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToDo
 */
export interface ToDo {
    /**
     * 
     * @type {number}
     * @memberof ToDo
     */
    readonly toDoId: number;
    /**
     * 
     * @type {string}
     * @memberof ToDo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ToDo
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ToDo
     */
    dueDatetime?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ToDo
     */
    isComplete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ToDo
     */
    owner?: number | null;
}

/**
 * Check if a given object implements the ToDo interface.
 */
export function instanceOfToDo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "toDoId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ToDoFromJSON(json: any): ToDo {
    return ToDoFromJSONTyped(json, false);
}

export function ToDoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToDo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'toDoId': json['to_do_id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'dueDatetime': !exists(json, 'due_datetime') ? undefined : (json['due_datetime'] === null ? null : new Date(json['due_datetime'])),
        'isComplete': !exists(json, 'is_complete') ? undefined : json['is_complete'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
    };
}

export function ToDoToJSON(value?: ToDo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'due_datetime': value.dueDatetime === undefined ? undefined : (value.dueDatetime === null ? null : value.dueDatetime.toISOString()),
        'is_complete': value.isComplete,
        'owner': value.owner,
    };
}

